eureka:  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:  
  port: 3333  
spring: 
  application:
    name: SHOPPING-SERVICE
  
  
  
#   ${PORT:1111}
    
#  server:
#    enableSelfPreservation: false  
    
#    ============
#    
#    server:  
#  port: ${PORT:1111}
#    
#eureka:  
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
# 
# 
#  server:
#    enableSelfPreservation: false  